name: check emails for points

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Restore cached folder
      id: cache-folder-restore
      uses: actions/cache/restore@v3
      with:
        path: |
          cache
        key: folder-key
    - name: run main
      run: |
        bash main.sh
      env:
        CONFIGURATION: ${{ secrets.CONFIGURATION }}
    - name: Save folder
      id: cache-folder-save
      uses: actions/cache/save@v3
      with:
        path: |
          cache
        key: ${{ steps.cache-folder-restore.outputs.cache-primary-key }}
